"""Emit package-local, IDE-readable resource lookups without type-checker plugins."""

import ast
from collections import Counter
from pathlib import Path


def generate_lookup(package_dir: Path, namespace: str) -> None:
    resources = []
    for file in sorted(package_dir.rglob("*.py")):
        module_parts = file.relative_to(package_dir).with_suffix("").parts
        if module_parts[-1] == "__init__":
            module_parts = module_parts[:-1]
        module = ".".join((namespace, *module_parts))
        for node in ast.parse(file.read_text()).body:
            if not isinstance(node, ast.ClassDef) or not any(
                isinstance(base, ast.Name) and base.id == "Resource" for base in node.bases
            ):
                continue
            defaults = {
                field.target.id: field.value.value
                for field in node.body
                if isinstance(field, ast.AnnAssign)
                and isinstance(field.target, ast.Name)
                and isinstance(field.value, ast.Constant)
                and isinstance(field.value.value, str)
            }
            if "api_version" in defaults and "kind" in defaults:
                resources.append((defaults["kind"], defaults["api_version"], module, node.name))
    if not resources:
        return
    resources.sort()
    counts = Counter(kind for kind, *_ in resources)
    lines = [
        "# Generated by cloudcoil-model-codegen; DO NOT EDIT",
        "from importlib import import_module",
        "from typing import TYPE_CHECKING, Literal, overload",
        "from cloudcoil.resources import Resource",
        "",
        "if TYPE_CHECKING:",
    ]
    for index, (_, _, module, name) in enumerate(resources):
        lines.append(f"    from {module} import {name} as _Resource{index}")
    lines.append("")
    for index, (kind, version, _, _) in enumerate(resources):
        lines += [
            "@overload",
            f"def get_model(kind: Literal[{kind!r}], *, api_version: Literal[{version!r}]) -> type[_Resource{index}]: ...",
            "",
        ]
        if counts[kind] == 1:
            lines += [
                "@overload",
                f"def get_model(kind: Literal[{kind!r}], *, api_version: Literal[''] = '') -> type[_Resource{index}]: ...",
                "",
            ]
    lines += [
        "@overload",
        "def get_model(kind: str, *, api_version: str = '') -> type[Resource]: ...",
        "",
        "_MODELS = {",
    ]
    for kind, version, module, name in resources:
        lines.append(f"    {(kind, version)!r}: {(module, name)!r},")
        if counts[kind] == 1:
            lines.append(f"    {(kind, '')!r}: {(module, name)!r},")
    lines += [
        "}",
        "",
        "def get_model(kind: str, *, api_version: str = '') -> type[Resource]:",
        '    """Look up a model in this package; specify api_version for ambiguous kinds."""',
        "    try:",
        "        module, name = _MODELS[kind, api_version]",
        "    except KeyError:",
        "        raise ValueError(f'Unknown or ambiguous resource {kind!r}; specify a supported api_version') from None",
        "    return getattr(import_module(module), name)",
        "",
    ]
    (package_dir / "_lookup.py").write_text("\n".join(lines))
    with (package_dir / "__init__.py").open("a") as output:
        output.write("\nfrom ._lookup import get_model as get_model\n")
