"""One-time, explicitly scoped publication of Cloudcoil 0.7.1 model drafts."""

import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time
import tomllib
import zipfile


VERSIONS = {
    "kubernetes": ["1.34.11", "1.35.8", "1.36.4", "1.37.0"],
    "cert-manager": ["1.21.1"],
    "fluxcd": ["2.9.5"],
    "kyverno": ["1.19.0"],
    "istio": ["1.31.0"],
    "keda": ["2.20.2"],
    "prometheus-operator": ["0.93.1"],
    "knative-eventing": ["1.23.0"],
    "knative-serving": ["1.23.0"],
    "kpack": ["0.18.0"],
    "sealed-secrets": ["0.39.1"],
    "velero": ["1.18.2"],
}


def run(*args):
    return subprocess.check_output(args, text=True).strip()


def api(path):
    return json.loads(run("gh", "api", path))


def select(releases, version, branch, sha=None):
    pattern = re.compile(re.escape(version) + r"\.([0-9]+)$")
    matches = [r for r in releases if pattern.fullmatch(r["tag_name"])
               and (r["target_commitish"] == branch
                    or (not r["draft"] and r["target_commitish"] == sha))
               and not r["prerelease"]]
    if not matches:
        raise RuntimeError(f"No release for {version} targeting {branch}")
    return max(matches, key=lambda r: int(pattern.fullmatch(r["tag_name"])[1]))


def branch_sha(repo, branch):
    return api(f"repos/{repo}/git/ref/heads/{branch}")["object"]["sha"]


def tag_sha(tag):
    result = subprocess.run(["git", "rev-parse", "--verify", f"refs/tags/{tag}^{{commit}}"],
                            capture_output=True, text=True)
    return result.stdout.strip() if result.returncode == 0 else None


def validate_metadata(version):
    project = tomllib.loads(Path("pyproject.toml").read_text())["project"]
    assert project["version"].startswith(version + "."), project["version"]
    assert "cloudcoil>=0.7.1,<0.8" in project["dependencies"], project["dependencies"]
    lock = tomllib.loads(Path("uv.lock").read_text())
    core = [p for p in lock["package"] if p["name"] == "cloudcoil"]
    assert len(core) == 1 and core[0]["version"] == "0.7.1", core
    generated = list(Path("cloudcoil/models").rglob("*.py"))
    assert generated, "No generated models"
    assert all(p.read_text().startswith(
        "# Generated by cloudcoil-model-codegen; DO NOT EDIT\n" if p.name == "_lookup.py"
        else "# Generated by cloudcoil-model-codegen v0.7.1\n")
        for p in generated), "Stale generated models"


def release(model, version):
    repo = f"cloudcoil/models-{model}"
    branch = "release-" + ".".join(version.split(".")[:2])
    source = branch_sha(repo, "main")
    deadline = time.monotonic() + 1200
    while True:
        runs = api(f"repos/{repo}/actions/workflows/update_releases.yml/runs?head_sha={source}&event=push&per_page=10")["workflow_runs"]
        matching = [r for r in runs if r["head_sha"] == source]
        if matching:
            latest = max(matching, key=lambda r: r["id"])
            if latest["status"] == "completed":
                assert latest["conclusion"] == "success", "Release generation failed"
                break
        assert time.monotonic() < deadline, "Timed out waiting for current release generation"
        print(f"Waiting for {repo} release generation at {source}", flush=True)
        time.sleep(15)
    pages = json.loads(run("gh", "api", "--paginate", "--slurp", f"repos/{repo}/releases?per_page=100"))
    sha = branch_sha(repo, branch)
    chosen = select([r for page in pages for r in page], version, branch, sha)
    tag = chosen["tag_name"]
    run("gh", "repo", "clone", repo, "models", "--", "--branch", branch)
    os.chdir("models")
    assert run("git", "rev-parse", "HEAD") == sha, "Branch moved during checkout"
    existing = tag_sha(tag)
    assert existing in (None, sha), f"{tag} already points to a different commit"
    validate_metadata(version)
    if not chosen["draft"]:
        assert existing == sha, "Published release is not this validated commit"
        print(f"Already published: {repo} {tag} at {sha}")
        return
    run("uv", "sync", "--locked", "--all-extras", "--dev")
    subprocess.run(["make", "lint", "test"], check=True)
    # Mirror the existing PyPI workflow's version substitution for this exact tag.
    path = Path("pyproject.toml")
    path.write_text(re.sub(r'^version = ".*"$', f'version = "{tag}"', path.read_text(),
                           count=1, flags=re.MULTILINE))
    subprocess.run(["uv", "build"], check=True)
    wheels = list(Path("dist").glob("*.whl"))
    assert len(wheels) == 1
    with zipfile.ZipFile(wheels[0]) as wheel:
        metadata = wheel.read(next(n for n in wheel.namelist() if n.endswith(".dist-info/METADATA"))).decode()
        assert f"\nVersion: {tag}\n" in metadata
        assert "cloudcoil" in metadata and "0.7.1" in metadata
        assert any(n.startswith("cloudcoil/models/") and n.endswith(".py") for n in wheel.namelist())
    assert branch_sha(repo, branch) == sha, "Branch moved during validation"
    assert branch_sha(repo, "main") == source, "Source changed during validation"
    current = api(f"repos/{repo}/releases/{chosen['id']}")
    assert current["draft"] and current["tag_name"] == tag and current["target_commitish"] == branch
    run("git", "fetch", "origin", "--tags")
    assert tag_sha(tag) in (None, sha), "Release tag moved during validation"
    # Pin the draft to the tested commit, eliminating branch movement at publication.
    run("gh", "release", "edit", tag, "--repo", repo, "--target", sha, "--draft=false")
    print(f"Published: {repo} {tag} at {sha}")


if __name__ == "__main__":
    model = sys.argv[1]
    assert model in VERSIONS, "Integration is outside this one-time release scope"
    for version in VERSIONS[model]:
        previous = Path.cwd()
        with tempfile.TemporaryDirectory() as directory:
            try:
                os.chdir(directory)
                release(model, version)
            finally:
                os.chdir(previous)
